In [129]:
import pandas as pd
import numpy as np
seg_risk = pd.read_csv("C:\\Users\\vizza\\Downloads\\01_loan_applications.csv")

In [126]:
copy_sr = seg_risk.copy()
copy_sr_1 = seg_risk.copy()
copy_sr_2=seg_risk.copy()

applicant_name COLUMN

In [37]:
seg_risk['applicant_name'].head(20)

0     PERSON_267
1     Person_142
2     PERSON_839
3     Person_175
4     PERSON_481
5     person_320
6     person_578
7      PERSON_94
8        UNKNOWN
9      Person_49
10    PERSON_807
11    person_331
12    Person_838
13    person_659
14           NaN
15    Person_555
16    Person_625
17    Person_6
18    person_298
19    PERSON_597
Name: applicant_name, dtype: str

In [ ]:
seg_risk['applicant_name'].isna().sum()

np.int64(42)

In [309]:
seg_risk['applicant_name'].value_counts()

applicant_name
Unknown       24
Person_807     2
Person_969     2
Person_883     2
Person_99      2
              ..
Person_767     1
Person_72      1
Person_908     1
Person_235     1
Person_37      1
Name: count, Length: 936, dtype: int64

In [28]:
seg_risk['applicant_name'].describe()

count         978
unique        940
top       unknown
freq            6
Name: applicant_name, dtype: object

In [6]:
seg_risk['applicant_name']=seg_risk['applicant_name'].str.lstrip()
seg_risk['applicant_name']=seg_risk['applicant_name'].str.rstrip()
seg_risk['applicant_name']=seg_risk['applicant_name'].str.strip()
seg_risk['applicant_name']=seg_risk['applicant_name'].str.lower().str.capitalize()

In [8]:
seg_risk['applicant_name']=seg_risk['applicant_name'].str.replace(r"^\s*$",'Unknown',regex=True)
rep_list=['?','Na']
seg_risk['applicant_name']=seg_risk['applicant_name'].replace(rep_list,'Unknown')

age COLUMN

In [312]:
seg_risk['age'].value_counts()

age
        44
59      25
29      24
27      24
53      24
        ..
262      1
5        1
7201     1
0        1
433      1
Name: count, Length: 66, dtype: int64

In [9]:
seg_risk['age']=seg_risk['age'].str.replace(r"[^0-9]",'',regex=True)
seg_risk['age']=seg_risk['age'].str.replace('00','')

In [ ]:
seg_risk['age']=pd.to_numeric(seg_risk['age'])
seg_risk['age']=seg_risk['age'].bfill().astype(int)

In [11]:
seg_risk['age']=seg_risk['age'].astype(str)

STRING CLEANING

In [12]:
seg_risk['gender']=seg_risk['gender'].str.lower().str.capitalize()
seg_risk['gender']=seg_risk['gender'].str.strip()

In [15]:
seg_risk['gender'].value_counts()

gender
Female        417
Male          346
Non-binary     96
Other          86
Unknown        36
Name: count, dtype: int64

In [14]:
gen_f=['F','f','female']
gen_m=['M','male','m']
gen_na=['?','Na','-']
seg_risk['gender']=seg_risk['gender'].replace(gen_f,'Female')
seg_risk['gender']=seg_risk['gender'].replace(gen_m,'Male')
seg_risk['gender']=seg_risk['gender'].replace(gen_na,'Unknown')
seg_risk['gender']=seg_risk['gender'].str.replace('other','Other')
seg_risk['gender']=seg_risk['gender'].str.replace(r"^\s*$",'Unknown',regex=True)

In [38]:
seg_risk['state'].value_counts()

state
New york        225
Texas           209
California      161
Florida          96
Illinois         66
Ohio             53
Miami            51
Georgia          49
Pennsylvania     40
Unknown          31
Name: count, dtype: int64

In [ ]:
seg_risk['state']=seg_risk['state'].str.replace('Tx','Texas')

In [ ]:
seg_risk['state']=seg_risk['state'].str.replace('Mi','Miami')

In [ ]:
seg_risk['state']=seg_risk['state'].str.replace('Ga','Georgia')

In [33]:
seg_risk['state']=seg_risk['state'].str.replace('Floridaorida','Florida')

In [ ]:
seg_risk['state']=seg_risk['state'].str.replace('Il','Illinois')

In [ ]:
seg_risk['state']=seg_risk['state'].str.strip()
seg_risk['state']=seg_risk['state'].str.lower().str.capitalize()

In [23]:
seg_risk['state']=seg_risk['state'].str.replace('Illinoislinois','Illinois')

In [25]:
seg_risk['state']=seg_risk['state'].str.replace('Oh','Ohio')

In [28]:
seg_risk['state']=seg_risk['state'].str.replace('Miamiami','Miami')

In [30]:
seg_risk['state']=seg_risk['state'].str.replace('Fl','Florida')

In [31]:
seg_ny=['Nc','Ny','N.y.']
seg_ca=['Ca','Calif.']
seg_risk['state']=seg_risk['state'].replace(seg_ny,'New york')
seg_risk['state']=seg_risk['state'].replace(seg_ca,'California')

In [35]:
seg_risk['state']=seg_risk['state'].str.replace('Pa','Pennsylvania')

In [36]:
seg_risk['state']=seg_risk['state'].str.replace(r"^\s*$",'Unknown',regex=True)

In [37]:
seg_na=['?','Na','-']
seg_risk['state']=seg_risk['state'].replace(seg_na,'Unknown')

In [39]:
seg_risk['employment_status']=seg_risk['employment_status'].str.strip()
seg_risk['employment_status']=seg_risk['employment_status'].str.lower().str.capitalize()

In [48]:
seg_risk['employment_status'].value_counts()

employment_status
Part-time        199
Self-employed    194
Employed         185
Contract         128
Unemployed       127
Retired          111
Unknown           35
Name: count, dtype: int64

In [41]:
seg_risk['employment_status']=seg_risk['employment_status'].str.replace('Na','Unknown')
seg_risk['employment_status']=seg_risk['employment_status'].str.replace('-','Unknown')
seg_risk['employment_status']=seg_risk['employment_status'].str.replace('?','Unknown')

In [43]:
seg_risk['employment_status']=seg_risk['employment_status'].str.replace('Self employed','Self-employed')
seg_risk['employment_status']=seg_risk['employment_status'].str.replace('Part time','Part-time')

In [44]:
seg_risk['employment_status']=seg_risk['employment_status'].str.replace(r"^\s*$",'Unknown',regex=True)

In [46]:
seg_risk['employment_status']=seg_risk['employment_status'].str.replace('SelfUnknownemployed','Self-employed')

In [47]:
seg_risk['employment_status']=seg_risk['employment_status'].str.replace('PartUnknowntime','Part-time')

In [49]:
seg_risk['loan_purpose']=seg_risk['loan_purpose'].str.strip()
seg_risk['loan_purpose']=seg_risk['loan_purpose'].str.lower().str.capitalize()

In [55]:
seg_risk['loan_purpose'].value_counts()

loan_purpose
Auto loan             200
Debt consolidation    175
Medical               134
Business              125
Education             115
Home improvement      114
Vacation               80
Unknown                36
Name: count, dtype: int64

In [51]:
seg_risk['loan_purpose']=seg_risk['loan_purpose'].str.replace(r"^\s*$",'Unknown',regex=True)

In [52]:
seg_risk['loan_purpose']=seg_risk['loan_purpose'].replace(['-','Na','?'],'Unknown')

In [53]:
seg_risk['loan_purpose']=seg_risk['loan_purpose'].replace('Edu','Education')

In [54]:
seg_risk['loan_purpose']=seg_risk['loan_purpose'].replace('Auto','Auto loan')

In [64]:
seg_risk['has_coborrower'].value_counts()

has_coborrower
Yes        497
No         451
Unknown     29
Name: count, dtype: int64

In [57]:
seg_risk['has_coborrower']=seg_risk['has_coborrower'].str.strip()
seg_risk['has_coborrower']=seg_risk['has_coborrower'].str.lower().str.capitalize()

In [59]:
seg_risk['has_coborrower']=seg_risk['has_coborrower'].replace(['True','Y','1',''],'Yes')

In [61]:
seg_risk['has_coborrower']=seg_risk['has_coborrower'].replace(['N','False','0',],'No')

In [63]:
seg_risk['has_coborrower']=seg_risk['has_coborrower'].replace(['-','Na','?'],'Unknown')

In [70]:
seg_risk['application_status'].value_counts()

application_status
Approved        314
Rejected        264
Pending         194
Under review    185
Unknown          25
Name: count, dtype: int64

In [66]:
seg_risk['application_status']=seg_risk['application_status'].str.strip()
seg_risk['application_status']=seg_risk['application_status'].str.lower().str.capitalize()

In [67]:
seg_risk['application_status']=seg_risk['application_status'].str.replace('Declined','Rejected')

In [68]:
seg_risk['application_status']=seg_risk['application_status'].replace(['?','-','Na'],'Unknown')

In [69]:
seg_risk['application_status']=seg_risk['application_status'].str.replace(r"^\s*$",'Unknown',regex=True)

INT. CLEANING

In [78]:
seg_risk['interest_rate_offered'].describe()
seg_risk['interest_rate_offered'].min()

np.float64(0.0367)

In [71]:
seg_risk['interest_rate_offered']=seg_risk['interest_rate_offered'].replace(r"^\s*$",'Unknown',regex=True)

In [80]:
seg_risk['interest_rate_offered'].isna().sum()

np.int64(0)

In [79]:
seg_risk['interest_rate_offered'].tail(30)

990     16.00
991     84.20
992     13.31
993     22.03
994     26.45
995     22.93
996     22.27
997     12.77
998     18.04
999     12.72
1000    94.00
1001    20.25
1002    23.94
1003    13.26
1004    25.02
1005    24.48
1006    15.17
1007    59.10
1008    13.20
1009    14.54
1010    18.37
1011    42.60
1012    20.25
1013    22.51
1014    84.60
1015    18.45
1016    24.49
1017    60.30
1018    17.67
1019    14.21
Name: interest_rate_offered, dtype: float64

In [383]:
seg_risk['interest_rate_offered'].value_counts()

interest_rate_offered
20.25    62
21.22     4
19.87     4
22.92     3
18.49     3
         ..
18.37     1
22.51     1
84.60     1
18.45     1
17.67     1
Name: count, Length: 788, dtype: int64

In [72]:
seg_risk['interest_rate_offered']=seg_risk['interest_rate_offered'].str.replace(r"[^0-9]",'',regex=True)

In [73]:
seg_risk['interest_rate_offered']=seg_risk['interest_rate_offered'].str[:2]+'.'+ seg_risk['interest_rate_offered'].str[2:]

In [74]:
seg_risk['interest_rate_offered']=seg_risk['interest_rate_offered'].replace('.','')

In [75]:
seg_risk['interest_rate_offered']=seg_risk['interest_rate_offered'].replace('Unknown','')

In [76]:
seg_risk['interest_rate_offered']=pd.to_numeric(seg_risk['interest_rate_offered'])

In [77]:
Q1 = seg_risk['interest_rate_offered'].quantile(0.25)
Q3 = seg_risk['interest_rate_offered'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

clean_median = seg_risk['interest_rate_offered'][
    (seg_risk['interest_rate_offered'] >= lower) & 
    (seg_risk['interest_rate_offered'] <= upper)
].median()


seg_risk['interest_rate_offered'] = seg_risk['interest_rate_offered'].fillna(clean_median)

In [91]:
seg_risk['loan_term_months'].value_counts()

loan_term_months
84    148
60    143
12    142
72    137
36    137
48    122
24    115
20     71
6       5
Name: count, dtype: int64

In [82]:
seg_risk['loan_term_months']=seg_risk['loan_term_months'].str.replace(r"[^0-9]",'',regex=True)

In [83]:
seg_risk['loan_term_months']=seg_risk['loan_term_months'].str.replace('00','')

In [84]:
seg_risk['loan_term_months']=seg_risk['loan_term_months'].str.replace('7201','72')

In [85]:
seg_risk['loan_term_months']=seg_risk['loan_term_months'].str.replace('364','36')

In [88]:
seg_risk['loan_term_months']=pd.to_numeric(seg_risk['loan_term_months'])

In [89]:
Q2=seg_risk['loan_term_months'].quantile(0.25)
Q4=seg_risk['loan_term_months'].quantile(0.75)
IQR_=Q4-Q2 
lower_=Q2-1.5*IQR
upper_=Q4+1.5*IQR   

clean= seg_risk['interest_rate_offered'][
    (seg_risk['interest_rate_offered'] >= lower_) & 
    (seg_risk['interest_rate_offered'] <= upper_)
].median()  

seg_risk['loan_term_months']=seg_risk['loan_term_months'].fillna(clean)

In [90]:
seg_risk['loan_term_months']=seg_risk['loan_term_months'].astype(int)

In [98]:
seg_risk['num_dependents'].value_counts()

num_dependents
3    192
5    159
6    143
1    137
0    131
4    130
2    128
Name: count, dtype: int64

In [93]:
seg_risk['num_dependents']=seg_risk['num_dependents'].str.replace('00','')

In [94]:
seg_risk['num_dependents']=seg_risk['num_dependents'].str.replace(r"[^0-9.]",'',regex=True)

In [95]:
seg_risk['num_dependents']=seg_risk['num_dependents'].str.replace(r"^0\.",'',regex= True)

In [96]:
seg_risk['num_dependents']=pd.to_numeric(seg_risk['num_dependents'])

In [97]:
seg_risk['num_dependents']=seg_risk['num_dependents'].fillna(seg_risk['num_dependents'].mean()).astype(int)

In [101]:
seg_risk['application_date'].tail(30)

990    2023-09-06
991    2018-09-15
992    2020-06-29
993    2021-07-22
994    2023-07-22
995    2018-07-02
996    2021-09-16
997    2021-02-08
998    2020-05-26
999    2019-07-28
1000   2021-08-17
1001   2023-10-31
1002   2020-02-02
1003   2018-06-26
1004   2022-04-23
1005   2018-12-15
1006   2021-10-05
1007   2022-09-27
1008   2020-11-08
1009   2021-03-08
1010   2023-01-03
1011   2018-04-01
1012   2021-11-06
1013   2024-04-16
1014   2021-10-13
1015   2022-11-30
1016   2023-03-13
1017   2020-05-24
1018   2022-11-25
1019   2020-02-22
Name: application_date, dtype: datetime64[us]

In [100]:
from dateutil import parser
seg_risk['application_date']=seg_risk['application_date'].apply(lambda x : parser.parse(x) if isinstance(x,str) else x)

In [106]:
seg_risk['dti_ratio'].value_counts()

dti_ratio
0.3220    3
0.5952    3
0.4809    3
0.3918    3
0.7365    3
         ..
0.5611    1
0.5683    1
0.1742    1
0.6879    1
0.2389    1
Name: count, Length: 866, dtype: int64

In [103]:
seg_risk['dti_ratio'].tail(30)

990          NaN
991        0.486
992       0.7299
993       0.3367
994       0.3321
995        0.688
996       0.1733
997       0.6354
998       0.3041
999       0.0739
1000      0.1042
1001      0.6786
1002    0.072USD
1003      0.1288
1004      0.0658
1005     0.6099$
1006      0.6486
1007      0.2423
1008        0.48
1009     0.2751$
1010      0.4206
1011      0.1325
1012      0.5611
1013      0.5683
1014      0.1742
1015      0.6879
1016      0.4643
1017      0.1708
1018      0.2389
1019      0.2966
Name: dti_ratio, dtype: str

In [104]:
seg_risk['dti_ratio']=seg_risk['dti_ratio'].str.replace(r"[^0-9.]",'',regex=True)

In [105]:
seg_risk['dti_ratio']=pd.to_numeric(seg_risk['dti_ratio'])

In [115]:
seg_risk['credit_score'].value_counts()

credit_score
568    80
354     7
839     6
348     6
548     6
       ..
507     1
567     1
401     1
361     1
394     1
Name: count, Length: 458, dtype: int64

In [108]:
seg_risk['credit_score']=seg_risk['credit_score'].str.replace(r"[^0-9]",'',regex=True)

In [109]:
seg_risk['credit_score'].tail(30)

990       841
991       460
992       411
993       606
994       428
995       397
996       684
997       328
998       817
999       610
1000      507
1001      719
1002      567
1003      688
1004      422
1005      685
1006      401
1007      447
1008      432
1009    44000
1010      800
1011      NaN
1012      619
1013      408
1014      361
1015      394
1016      376
1017      727
1018      733
1019      345
Name: credit_score, dtype: str

In [110]:
seg_risk['credit_score']=seg_risk['credit_score'].str.replace('.0','',regex = False )

In [111]:
seg_risk['credit_score']=seg_risk['credit_score'].str[:3]

In [112]:
seg_risk['credit_score']=pd.to_numeric(seg_risk['credit_score'])

In [113]:
mean_score=seg_risk['credit_score'].mean()
seg_risk['credit_score'] = seg_risk['credit_score'].fillna(mean_score)

In [114]:
seg_risk['credit_score']=seg_risk['credit_score'].astype(int)

In [116]:
seg_risk['age']=seg_risk['age'].str[:2]

In [117]:
seg_risk['age'].tail(30)

990     64
991     35
992     18
993     60
994     21
995     57
996     42
997     28
998     28
999     40
1000    24
1001    46
1002    55
1003    26
1004    51
1005    72
1006    68
1007    59
1008    74
1009    22
1010    46
1011    27
1012    59
1013    48
1014    58
1015    56
1016    72
1017    58
1018    43
1019    62
Name: age, dtype: str

In [118]:
seg_risk['age']=pd.to_numeric(seg_risk['age'])
seg_risk['age'].isna().sum()

np.int64(0)

In [119]:
mean_age=seg_risk['age'].mean()
seg_risk['age']=seg_risk['age'].fillna(mean_age)
seg_risk['age']=seg_risk['age'].astype(int)

In [120]:
seg_risk

,application_id,applicant_name,age,gender,state,employment_status,annual_income,loan_amount_requested,loan_purpose,credit_score,dti_ratio,application_date,num_dependents,has_coborrower,loan_term_months,interest_rate_offered,application_status
0,APP40443,Person_267,29,Male,Ohio,Contract,97139.19,45566.38,Home improvement,837,0.4559,2019-03-11,5,No,84,25.61,Under review
1,APP73185,Person_142,52,Male,Texas,Part-time,142190.55,79336.51,Education,641,0.5273,2022-11-29,1,Yes,48,22.92,Pending
2,APP30354,Person_839,37,Male,Texas,Unemployed,74.32907,8173.62,Auto loan,811,0.4641,2019-06-28,5,Yes,24,19.81,Rejected
3,APP85846,Person_175,73,Male,California,Part-time,146598.65,23971.19,Business,799,0.3298,2022-11-30,4,No,48,21.21,Rejected
4,APP23320,Person_481,27,Male,Illinois,Unemployed,210304.68,72058.19,Debt consolidation,357,0.0523,2019-12-02,4,Yes,72,59.80,Approved
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,APP48574,Person_767,56,Non-binary,New york,Employed,216626.94,8479.47,Medical,394,0.6879,2022-11-30,4,Yes,20,18.45,Pending
1016,APP86122,Person_72,72,Female,California,Part-time,4897521.0,65777.07,Business,376,0.4643,2023-03-13,6,Yes,20,24.49,Approved
1017,APP29367,Person_908,58,Unknown,New york,Unemployed,202151.44,5714.92,Auto loan,727,0.1708,2020-05-24,1,Yes,36,60.30,Pending
1018,APP37973,Person_235,43,Male,New york,Contract,219380.78,76258.96,Vacation,733,0.2389,2022-11-25,5,Yes,24,17.67,Approved
1019,APP23587,Person_37,62,Other,NaN,Employed,188563.38,27268.97,Vacation,345,0.2966,2020-02-22,2,Yes,12,14.21,Pending

In [477]:
seg_risk['annual_income'].value_counts()

annual_income
UNKNOWN      9
unknown      7
na           6
?            6
-            3
            ..
216626.94    1
4897521.0    1
202151.44    1
219380.78    1
188563.38    1
Name: count, Length: 939, dtype: int64

In [487]:
seg_risk['annual_income'].head(30)

0      97139.19000
1     142190.55000
2         74.32907
3     146598.65000
4     210304.68000
5      28151.83000
6      96667.46000
7     189562.26000
8      19268.91000
9     158531.44000
10             NaN
11    114744.13000
12    157908.12000
13     68461.85000
14     40268.60000
15    232672.27000
16    189733.84000
17    111675.93000
18     64398.68000
19     98138.88000
20    131591.52000
21    193036.19000
22    214738.46000
23    115662.85000
24    136656.43000
25    149059.79000
26    118555.55000
27    119570.72000
28             NaN
29    247790.04000
Name: annual_income, dtype: float64

In [121]:
seg_risk['annual_income']=seg_risk['annual_income'].str.strip()
seg_risk['annual_income']=seg_risk['annual_income'].str.replace(r"[^0-9.]",'',regex=True)

In [122]:
seg_risk['annual_income']=pd.to_numeric(seg_risk['annual_income'])

In [125]:
seg_risk

,application_id,applicant_name,age,gender,state,employment_status,annual_income,loan_amount_requested,loan_purpose,credit_score,dti_ratio,application_date,num_dependents,has_coborrower,loan_term_months,interest_rate_offered,application_status
0,APP40443,Person_267,29,Male,Ohio,Contract,97139.19,45566.38,Home improvement,837,0.4559,2019-03-11,5,No,84,25.61,Under review
1,APP73185,Person_142,52,Male,Texas,Part-time,142190.55,79336.51,Education,641,0.5273,2022-11-29,1,Yes,48,22.92,Pending
2,APP30354,Person_839,37,Male,Texas,Unemployed,74329.07,8173.62,Auto loan,811,0.4641,2019-06-28,5,Yes,24,19.81,Rejected
3,APP85846,Person_175,73,Male,California,Part-time,146598.65,23971.19,Business,799,0.3298,2022-11-30,4,No,48,21.21,Rejected
4,APP23320,Person_481,27,Male,Illinois,Unemployed,210304.68,72058.19,Debt consolidation,357,0.0523,2019-12-02,4,Yes,72,59.80,Approved
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,APP48574,Person_767,56,Non-binary,New york,Employed,216626.94,8479.47,Medical,394,0.6879,2022-11-30,4,Yes,20,18.45,Pending
1016,APP86122,Person_72,72,Female,California,Part-time,4897521.00,65777.07,Business,376,0.4643,2023-03-13,6,Yes,20,24.49,Approved
1017,APP29367,Person_908,58,Unknown,New york,Unemployed,202151.44,5714.92,Auto loan,727,0.1708,2020-05-24,1,Yes,36,60.30,Pending
1018,APP37973,Person_235,43,Male,New york,Contract,219380.78,76258.96,Vacation,733,0.2389,2022-11-25,5,Yes,24,17.67,Approved
1019,APP23587,Person_37,62,Other,NaN,Employed,188563.38,27268.97,Vacation,345,0.2966,2020-02-22,2,Yes,12,14.21,Pending

In [124]:
seg_risk.loc[seg_risk['annual_income']<1000,'annual_income']*=1000

In [127]:
seg_risk.to_csv('cleaned_csv.csv',index= False)

In [132]:
sec_cleaned= pd.read_csv(r"C:\Users\\vizza\\OneDrive\\Desktop\\Data_Sci\\cleaned_csv.csv")

In [136]:
sec_cleaned.info()

<class 'pandas.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   application_id         1020 non-null   str
 1   applicant_name         978 non-null    str
 2   age                    1020 non-null   int64
 3   gender                 981 non-null    str
 4   state                  981 non-null    str
 5   employment_status      979 non-null    str
 6   annual_income          951 non-null    float64
 7   loan_amount_requested  983 non-null    str
 8   loan_purpose           979 non-null    str
 9   credit_score           1020 non-null   int64
 10  dti_ratio              950 non-null    float64
 11  application_date       1020 non-null   str
 12  num_dependents         1020 non-null   int64
 13  has_coborrower         977 non-null    str
 14  loan_term_months       1020 non-null   int64
 15  interest_rate_offered  1020 non-null   float64
 16  application_status     982 non-null    str
dtypes: float64(3), int64(4), str(10)
memory usage: 135.6 KB